/**
 * Describes all buildings and thir upgrades in the game.
 */
const buildings = [
    {
        name: "Obdachloser",
        namePlural: "Obdachlose",
        upgrades: [
            "Vodka",
            "Agressives Betteln",
            "Handschuhe",
            "Sicherheitsflipflops",
            "'ne Mark",
            "Crack",
            "Obdachlosenheim",
            "Kaffee",
            "Schlafsack",
            "Br&uuml;cke",
            "Bahnhof",
            "Stammplatz",
            "Netto",
            "Hund",
            "Polizeieskorte",
            "lorem ipsum",
            "lorem ipsum",
            "lorem ipsum",
            "lorem ipsum",
            "lorem ipsum",
        ]
    },
    {
        name: "Festivalg&auml;nger",
        namePlural: "Festivalg&auml;nger",
        upgrades: [
            "Happiness-Ticket",
            "Auto",
            "Wacken-Ticket",
            "Trichter",
            "Zelt",
            "Sex",
            "Dreistheit",
            "Ritalin",
            "kein Schlaf",
            "fehlender Geruchssinn",
            "Dosenravioli",
            "Musikgeschmack",
            "Energy-Drinks",
            "pubert&auml;res Verhalten",
            "M&uuml;lls&auml;cke",
            "lorem ipsum",
            "lorem ipsum",
            "lorem ipsum",
            "lorem ipsum",
        ]
    },
    {
        name: "Pfandautomat",
        namePlural: "Pfandautomaten",
        upgrades: [
            "Breitere &ouml;ffnung",
            "Anti-Stau-System",
            "Schlaue Kunden",
            "Hilfsbereite Mitarbeiter",
            "Assembler",
            "Peitschen",
            "Diebstahlschutz",
            "Zweite &ouml;ffnung",
            "Deposit Droid",
            "Bottle Bounty Bot",
            "Can Credit Contraption",
            "Refund Robot",
            "Coin-Return Wizard",
            "Refundinator Machine",
            "Penny Pincher's Pal",
            "Empties Enchanter",
            "Token Treasure Trove",
            "Bottle Bucks Buddy",
        ],
    },
    {
        name: "Glascontainer",
        namePlural: "Glascontainer",
        upgrades: [
            "W&ouml;chentliche Leerung",
            "T&auml;gliche Leerung",
            "Zweiter Boden",
            "St&uuml;ndliche Leerung",
            "Besserer Standort",
            "Schwarzes Loch",
            "Glass Goblin Hideout",
            "Bottle Bank Bonanza",
            "Jar Jamboree",
            "Canister Carnival",
            "Pane Party Pitstop",
            "Clinker Collector's Corner",
            "Shatter Stopover Spot",
            "Mug Mingle Zone",
            "Pint Pot Parade Ground",
        ],
    },
    {
        name: "Supermarkt",
        namePlural: "Superm&auml;rkte",
        upgrades: [
            "Kinderarbeit",
            "Verbessertes Kassensystem",
            "Dumme Kunden",
            "Autobahnanbindung",
            "Manager",
            "Aisle Adventures",
            "Shopping Cart Shenanigans",
            "Checkout Line Comedy",
            "Cereal Aisle Surprises",
            "Frozen Food Follies",
            "Coupon Craziness",
            "Express Lane Exasperation",
            "Price Tag Perplexities",
            "Produce Section Peculiarities",
        ],
    },
    {
        name: "HaDiKo",
        namePlural: "HaDiKos",
        upgrades: [
            "GeMa",
            "Andr&eacute;",
            "i2",
            "K5 Bar",
            "K2 Hausfest",
            "K7",
            "Dormitory Drama",
            "Residence Hall Romp",
            "Roommate Roulette",
            "Common Area Capers",
            "Cafeteria Chronicles",
            "Launderette Lunacy",
            "Quiet Hours Quandary",
            "RA Revelations",
            "Freshman Follies",
        ],
    },
    {
        name: "M&uuml;lldeponie",
        namePlural: "M&uuml;lldeponien",
        upgrades: [
            "Rattenk&ouml;der",
            "Afrikaner",
            "fehlende Umweltauflagen",
            "Kipplader",
            "Abfallberg",
            "Schrottplatz",
            "M&uuml;llkippe",
            "Trash-Palast",
            "Deponie",
            "Kl&uuml;ngelhaufen",
            "Sammelsurium der Sinnlosigkeit",
            "Ressourcen-Resort",
            "Plastik-Paradies",
            "Unordnungs-Olympics",
        ],
    },
    {
        name: "Flaschenfabrik",
        namePlural: "Flaschenfabriken",
        upgrades: [
            "Produktionspapierwalze",
            "Zahnrad-Zentrale",
            "Fließband-Fieber",
            "Roboter-Rendezvous",
            "Qualm-Quelle",
            "Schrauben-Sinfonie",
            "Ziegelstein-Zauberei",
            "Fabrik-Fata Morgana",
            "Dampfmaschinen-Disco",
            "Rostiges R&auml;tselreich",
            "Montage-M&auml;rchenland",
            "Zylinder-Zirkus",
            "Schrauben-Spaßstation",
        ],
    },
    {
        name: "Panama",
        namePlural: "Panamas",
        upgrades: [
            "Strand voller Pfand",
            "Touristenf&uuml;hrer",
            "Panamapapier",
            "Panamakappe",
            "Panamarama",
            "Panamarama-Drama",
            "Panamadrama",
            "Panamabande",
            "Panamamama",
            "Panama-Hut",
            "Panama-Kanal",
            "Panamahose",
        ],
    },
    {
        name: "Ozean",
        namePlural: "Ozeane",
        upgrades: [
            "Plastiktitanik",
            "Wellenwirbel",
            "Meeresmonster",
            "Schatzsuche",
            "Gezeitengepl&auml;nkel",
            "Walfischtango",
            "Neptuns Spielplatz",
            "Muschelmagie",
            "Seegurken-Spuk",
            "Krakenkaraoke",
            "Pinguin-Poolparty",
        ],
    },
    {
        name: "Zweite Erde",
        namePlural: "Zweite Erden",
        upgrades: [
            "Doppelg&auml;nger-Planet",
            "Terra Dos",
            "Bizarro-Erde",
            "Erdling 2.0",
            "Erd-Zwo",
            "Die Andere Welt",
            "Erdopia",
            "Erde Deluxe",
            "Terra Zwei: Die R&uuml;ckkehr",
            "Planet Xerox",
        ],
    }
];

export { buildings }